### PR TITLE
Adding authentication to the admin portal page

### PR DESCRIPTION
**Pull request by iamyume**

### CODE REVIEW

**Comment by tisidro** [comment]
Eugene, everything looks good to me--there are some things I still don't fully grasp but as far as testing the Admin portal it's all functional! We discussed adding a Logout button and there is an error "TypeError: setCounty is not a function" that appears when you go to update a record and click any field to update data (not just the county field). Thanks! :)

**Comment by iamyume** [comment]
addressed the issue of a logout button and fixed the update record feature. Should be good to go now.

**Comment by tisidro** [comment]
That's great! Should we merge the branches now--I see something about you wanting to merge 15 commits into main from this authentication branch, but do I need to do anything? Thanks so much :)

**Comment by tisidro** [comment]
I see the merge pull request, should I just click that and go for it?

**Comment by iamyume** [comment]
If the changes looks good to you and testing it out locally works then usually it’s good to merge. Bigger groups have official code reviews and unit tests to pass but for our needs if you tested it and looks good then go ahead and merge it.

**Comment by tisidro** [comment]
Thanks, I have pulled it and will test then let you know when I merge! :)

**Pull request merged**
